/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelOptionsAccessory.java
 *
 * Created on 21-Feb-2009, 19:03:00
 */

package aspectedit.frames.action.accessories;

import aspectedit.level.LevelFormat;
import aspectedit.util.OffsetSpinnerBuilder;
import javax.swing.JPanel;

/**
 *
 * @author mark
 */
public class OpenLevelOptionsAccessory extends JPanel {

    /** Creates new form LevelOptionsAccessory */
    public OpenLevelOptionsAccessory() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    public int getOffset() {
        return (Integer) offsetSpinner.getValue();
    }

    public void setOffset(int offset) {
        offsetSpinner.setValue(offset);
    }
    
    public LevelFormat getLevelFormat() {
        if(s2Radio.isSelected()) {
            return LevelFormat.S2;
        } else if(scRadio.isSelected()) {
            return LevelFormat.SC;
        } else {
            return LevelFormat.TT;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s2Radio = new javax.swing.JRadioButton();
        ttRadio = new javax.swing.JRadioButton();
        offsetSpinner = OffsetSpinnerBuilder.build();
        scRadio = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel1.setText("Offset:");

        jLabel2.setText("Compression:");

        buttonGroup1.add(s2Radio);
        s2Radio.setSelected(true);
        s2Radio.setText("Sonic 2");

        buttonGroup1.add(ttRadio);
        ttRadio.setText("Triple Trouble");

        buttonGroup1.add(scRadio);
        scRadio.setText("Sonic Chaos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(scRadio)
                    .addComponent(s2Radio, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(offsetSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s2Radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ttRadio)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner offsetSpinner;
    private javax.swing.JRadioButton s2Radio;
    private javax.swing.JRadioButton scRadio;
    private javax.swing.JRadioButton ttRadio;
    // End of variables declaration//GEN-END:variables

}
