/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelOptionsAccessory.java
 *
 * Created on 21-Feb-2009, 19:03:00
 */

package aspectedit.frames.action.accessories;

import javax.swing.JPanel;

/**
 *
 * @author mark
 */
public class SaveTilesetOptionsAccessory extends JPanel {

    /** Creates new form LevelOptionsAccessory */
    public SaveTilesetOptionsAccessory() {
        initComponents();
    }
    
    public boolean isCompressed() {
        return compressedRadio.isSelected();
    }

    public void setCompressed(boolean compressed) {
        compressedRadio.setSelected(compressed);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        compressedRadio = new javax.swing.JRadioButton();
        uncompressedRadio = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel2.setText("Compression:");

        buttonGroup1.add(compressedRadio);
        compressedRadio.setSelected(true);
        compressedRadio.setText("Compressed");

        buttonGroup1.add(uncompressedRadio);
        uncompressedRadio.setText("Uncompressed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uncompressedRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(compressedRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(compressedRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uncompressedRadio)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton compressedRadio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton uncompressedRadio;
    // End of variables declaration//GEN-END:variables

}
