/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelOptionsAccessory.java
 *
 * Created on 21-Feb-2009, 19:03:00
 */

package aspectedit.frames.action.accessories;

import aspectedit.level.LevelFormat;
import javax.swing.JPanel;

/**
 *
 * @author mark
 */
public class SaveLevelOptionsAccessory extends JPanel {

    /** Creates new form LevelOptionsAccessory */
    public SaveLevelOptionsAccessory() {
        initComponents();
    }

    public void setLevelFormat(LevelFormat format) {
        switch(format) {
            case S2:
                s2Radio.setSelected(true);
                break;
            case SC:
                scRadio.setSelected(true);
                break;
            case TT:
                ttRadio.setSelected(true);
                break;
        }
    }
    public LevelFormat getLevelFormat() {
        if(s2Radio.isSelected()) {
            return LevelFormat.S2;
        } else if(scRadio.isSelected()) {
            return LevelFormat.SC;
        } else {
            return LevelFormat.TT;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        s2Radio = new javax.swing.JRadioButton();
        ttRadio = new javax.swing.JRadioButton();
        scRadio = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel2.setText("Compression:");

        buttonGroup1.add(s2Radio);
        s2Radio.setSelected(true);
        s2Radio.setText("Sonic 2");

        buttonGroup1.add(ttRadio);
        ttRadio.setText("Triple Trouble");

        buttonGroup1.add(scRadio);
        scRadio.setText("Sonic Chaos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s2Radio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(scRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ttRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s2Radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ttRadio)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton s2Radio;
    private javax.swing.JRadioButton scRadio;
    private javax.swing.JRadioButton ttRadio;
    // End of variables declaration//GEN-END:variables

}
