/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelOptionsAccessory.java
 *
 * Created on 21-Feb-2009, 19:03:00
 */

package aspectedit.frames.action.accessories;

import aspectedit.palette.PaletteFormat;
import javax.swing.JPanel;

/**
 *
 * @author mark
 */
public class SavePaletteOptionsAccessory extends JPanel {

    /** Creates new form LevelOptionsAccessory */
    public SavePaletteOptionsAccessory() {
        initComponents();
    }
    
    public PaletteFormat getPaletteFormat() {
        if(gimpRadio.isSelected()) {
            return PaletteFormat.GIMP;
        } else if(smsRadio.isSelected()) {
            return PaletteFormat.SMS;
        } else {
            return PaletteFormat.GG;
        }
    }

    public void setPaletteFormat(PaletteFormat format) {

        switch(format) {
            default:
            case SMS: smsRadio.setSelected(true); break;
            case GG: ggRadio.setSelected(true); break;
            case GIMP: gimpRadio.setSelected(true); break;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        smsRadio = new javax.swing.JRadioButton();
        ggRadio = new javax.swing.JRadioButton();
        gimpRadio = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel2.setText("Type:");

        buttonGroup1.add(smsRadio);
        smsRadio.setSelected(true);
        smsRadio.setText("SMS");

        buttonGroup1.add(ggRadio);
        ggRadio.setText("GG");

        buttonGroup1.add(gimpRadio);
        gimpRadio.setText("GIMP (GPL)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ggRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(smsRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(gimpRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(smsRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ggRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gimpRadio)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ggRadio;
    private javax.swing.JRadioButton gimpRadio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton smsRadio;
    // End of variables declaration//GEN-END:variables

}
